### ISSUE TITLE
Docker image and tagging for Orchestra

### ISSUE THREAD

**Issue by seandavi** [ahl27/CompGenomicsBioc2022#1]
Hi, @ahl27. I noticed that your workshop wasn't launching and took a quick look. Orchestra uses a fixed image name. I've changed the image name to `ghcr.io/ahl27/compgenomicsbioc2022:728221013` so your workshop should launch now. However, if you make changes or updates to the docker image, you'll either want to use the same tag or, better, use the tagging you are using now and add a `:latest` tag. If you go with the latter approach, let me know so that I can update Orchestra to use the `:latest` tag.

**Comment by ahl27** [comment]
Aha, that makes sense--I didn't realize that it worked that way. Thanks for looking into this in advance for me, Sean.

I've updated the docker image with a new `ghcr.io/ahl27/compgenomicsbioc2022:latest` tag, and I'll continue pushing to `:latest` going forward. If you don't have time to change it prior to tomorrow it's not an issue, I'm not planning to make any adjustments to my docker container between today and tomorrow.

Thanks again!

**Comment by seandavi** [comment]
I made the update. You should get `:latest` from here on out. Thanks for your quick fix.
